### PR TITLE
Add jitter

### PR DESCRIPTION
**Pull request by fhielpos**
Adds requeues for PolicyManifest and PolicyReport controllers. Also adds the requeue time for when the PolicyManifest cache is empty.

### CODE REVIEW

**Comment by Strigix** [comment]
I want @stone-z to look at this as well.
Because if I remember correctly, there is some sort of jitter function already that  we could use?

**Review by stone-z — APPROVED** [review]
Stefan is right, this isn't jitter, just normal re-queuing, but that's also important so :+1:

**Comment by Strigix** [comment]
Looks good to me, @stone-z could you explain the mathiness around Jitter to me/us tomorrow?

**Review by stone-z — APPROVED** [review]
Consider it jittered :tada:

**Pull request merged**
