### PR TITLE
Use UID instead of manually set names

### PR DESCRIPTION
**Pull request by fhielpos**

### CODE REVIEW

**Comment by fhielpos** [comment]
I don't think we need to rework the Get/Create logic here. At least for now.

**Review by stone-z — COMMENTED** [review]
Does this work? Aren't there collisions if there are multiple policies or targets in a policy report?

**Comment by fhielpos** [comment]
Oh, yes, I used the wrong UID 🙈

**Comment by fhielpos** [comment]
Working 🚀

**Pull request merged**
